### ISSUE TITLE
Agent failed to run: server returned non-202 status: 200

### ISSUE THREAD

**Issue by stefansdconsult** [cxnturi0n/convoC2#1]
No Connection between Agent und Server. Server is listening an Port 80

Agent initialized: {WIN11****C\user c38582bafcf67921897fc89d114d6c20}
Agent failed to run: server returned non-202 status: 200

**Comment by cxnturi0n** [comment]
Are you sure the webhook URL is correct?

**Comment by stefansdconsult** [comment]
My false. Now I got it working.
