### ISSUE TITLE
Error creating the Teams Chat URL

### ISSUE THREAD

**Issue by stefansdconsult** [cxnturi0n/convoC2#2]
When trying to create the URL:
url_generate "id":"8:orgid:34f96c10-68e0-4438-8c9e-xxxxxxxxxx" "id":"8:orgid:8c1f5274-8841-4097-9cc1-xxxxxxxxxxxx"

I get the following error message
**error: no** location header found in the response

Burp Suite output as the basis for URL:

{
"members":[
{"id":"8:orgid:34f96c10-68e0-4438-8c9e-xxxxxxxx",
"role":"Admin"},
{"id":"8:orgid:8c1f5274-8841-4097-9cc1-xxxxxxxx",
"role":"Admin"}
],

**Comment by cxnturi0n** [comment]
You have to run: 

`url_generate 8:orgid:34f96c10-68e0-4438-8c9e-xxxxxxxxxx 8:orgid:8c1f5274-8841-4097-9cc1-xxxxxxxxxxxx`
